
export const INDUSTRY_KEYWORDS = {
    "Accommodation Services": ["hotel", "resort", "lodging", "hospitality", "accommodation", "inn", "motel", "hostel", "bed and breakfast", "bnb"],
    "Administrative and Support Services": ["administrative", "support services", "business services", "office support", "facilities management", "call center", "outsourcing"],
    "Construction": ["construction", "contractor", "builder", "building", "infrastructure", "civil engineering", "architecture", "renovation"],
    "Consumer Services": ["consumer services", "retail services", "customer service", "personal services", "consumer goods", "hairdresser", "salon", "laundry"],
    "Education": ["education", "school", "university", "college", "academic", "learning", "training", "educational", "institute", "student", "teacher", "professor", "faculty"],
    "Entertainment Providers": ["entertainment", "media", "film", "television", "music", "gaming", "sports", "recreation", "amusement", "cinema", "theater"],
    "Farming, Ranching, Forestry": ["farming", "ranching", "forestry", "agriculture", "agricultural", "farm", "ranch", "crop", "livestock", "forest"],
    "Financial Services": ["financial", "banking", "finance", "investment", "insurance", "accounting", "wealth management", "credit", "loan", "mortgage", "fintech", "audit", "tax", "cpa"],
    "Government Administration": ["government", "public sector", "municipal", "federal", "state", "public administration", "civic", "ministry", "department"],
    "Holding Companies": ["holding", "holdings", "investment company", "conglomerate", "group"],
    "Hospitals and Health Care": ["hospital", "healthcare", "health care", "medical", "clinic", "health", "pharmaceutical", "pharma", "biotech", "nursing", "physician", "doctor", "surgeon", "dentist"],
    "Manufacturing": ["manufacturing", "manufacturer", "production", "factory", "industrial", "assembly", "fabrication"],
    "Oil, Gas, and Mining": ["oil", "gas", "petroleum", "mining", "energy", "drilling", "refinery", "extraction", "mineral"],
    "Professional Services": ["professional services", "consulting", "legal", "law firm", "advisory", "professional", "attorney", "lawyer", "consultant"],
    "Real Estate and Equipment Rental Services": ["real estate", "property", "realtor", "rental", "leasing", "equipment rental", "property management", "broker"],
    "Retail": ["retail", "store", "shop", "merchandise", "e-commerce", "commerce", "shopping", "supermarket", "mall"],
    "Technology, Information and Media": ["technology", "tech", "software", "it ", "information technology", "digital", "computer", "saas", "cloud", "data", "internet", "web", "app", "developer", "programming", "ai", "artificial intelligence", "machine learning", "cybersecurity", "blockchain", "network", "telecom"],
    "Transportation, Logistics, Supply Chain and Storage": ["transportation", "logistics", "shipping", "freight", "delivery", "supply chain", "warehouse", "storage", "trucking"],
    "Utilities": ["utilities", "utility", "electric", "power", "water", "gas utility", "energy utility", "public utility"],
    "Wholesale": ["wholesale", "distributor", "distribution", "wholesaler", "bulk", "import", "export", "trading"],
    "Marketing & Advertising": ["marketing", "advertising", "pr", "public relations", "branding", "creative agency", "digital marketing", "market research", "seo", "social media", "content creator", "copywriter"],
    "Food & Beverage Services": ["food", "beverage", "restaurant", "cafe", "dining", "catering", "brewery", "winery", "bar", "bakery", "culinary", "chef", "cook"],
    "Automotive": ["automotive", "automobile", "car", "vehicle", "dealership", "motor", "auto repair", "mechanic"],
    "Non-profit & Organization": ["non-profit", "nonprofit", "charity", "foundation", "social organization", "ngo", "philanthropy", "association", "society", "community organization"],
    "Design & Arts": ["design", "graphic design", "interior design", "creative", "art", "photography", "artist", "illustrator", "animator"],
};
